[project]
name = "my-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "indiragothi", email = "indiragothi007@gmail.com" }
]
requires-python = ">=3.12.2"
dependencies = [
    "dotenv>=0.9.9",
    "duckduckgo-search>=8.1.1",
    "ipykernel>=7.3.0",
    "langchain-community>=0.4.2",
    "langchain-google-genai>=4.4.0",
    "langgraph>=1.2.11",
    "numpy>=2.5.3",
    "pamdas>=0.1.0",
]

[project.scripts]
my-project = "my_project:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
